/*
PingOne Platform API - PingOne MFA

The PingOne Platform API covering the PingOne MFA service

API version: 2023-06-29
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mfa

import (
	"encoding/json"
)

// checks if the DeviceAuthenticationPolicyCommonFido2Failure type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceAuthenticationPolicyCommonFido2Failure{}

// DeviceAuthenticationPolicyCommonFido2Failure struct for DeviceAuthenticationPolicyCommonFido2Failure
type DeviceAuthenticationPolicyCommonFido2Failure struct {
	// The maximum number of times that authentication can fail before user is blocked for the specified period. Minimum is `1`, maximum is `7`.
	Count    *int32                                                `json:"count,omitempty"`
	CoolDown *DeviceAuthenticationPolicyCommonFido2FailureCoolDown `json:"coolDown,omitempty"`
}

// NewDeviceAuthenticationPolicyCommonFido2Failure instantiates a new DeviceAuthenticationPolicyCommonFido2Failure object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceAuthenticationPolicyCommonFido2Failure() *DeviceAuthenticationPolicyCommonFido2Failure {
	this := DeviceAuthenticationPolicyCommonFido2Failure{}
	return &this
}

// NewDeviceAuthenticationPolicyCommonFido2FailureWithDefaults instantiates a new DeviceAuthenticationPolicyCommonFido2Failure object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceAuthenticationPolicyCommonFido2FailureWithDefaults() *DeviceAuthenticationPolicyCommonFido2Failure {
	this := DeviceAuthenticationPolicyCommonFido2Failure{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *DeviceAuthenticationPolicyCommonFido2Failure) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceAuthenticationPolicyCommonFido2Failure) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *DeviceAuthenticationPolicyCommonFido2Failure) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *DeviceAuthenticationPolicyCommonFido2Failure) SetCount(v int32) {
	o.Count = &v
}

// GetCoolDown returns the CoolDown field value if set, zero value otherwise.
func (o *DeviceAuthenticationPolicyCommonFido2Failure) GetCoolDown() DeviceAuthenticationPolicyCommonFido2FailureCoolDown {
	if o == nil || IsNil(o.CoolDown) {
		var ret DeviceAuthenticationPolicyCommonFido2FailureCoolDown
		return ret
	}
	return *o.CoolDown
}

// GetCoolDownOk returns a tuple with the CoolDown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceAuthenticationPolicyCommonFido2Failure) GetCoolDownOk() (*DeviceAuthenticationPolicyCommonFido2FailureCoolDown, bool) {
	if o == nil || IsNil(o.CoolDown) {
		return nil, false
	}
	return o.CoolDown, true
}

// HasCoolDown returns a boolean if a field has been set.
func (o *DeviceAuthenticationPolicyCommonFido2Failure) HasCoolDown() bool {
	if o != nil && !IsNil(o.CoolDown) {
		return true
	}

	return false
}

// SetCoolDown gets a reference to the given DeviceAuthenticationPolicyCommonFido2FailureCoolDown and assigns it to the CoolDown field.
func (o *DeviceAuthenticationPolicyCommonFido2Failure) SetCoolDown(v DeviceAuthenticationPolicyCommonFido2FailureCoolDown) {
	o.CoolDown = &v
}

func (o DeviceAuthenticationPolicyCommonFido2Failure) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceAuthenticationPolicyCommonFido2Failure) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.CoolDown) {
		toSerialize["coolDown"] = o.CoolDown
	}
	return toSerialize, nil
}

type NullableDeviceAuthenticationPolicyCommonFido2Failure struct {
	value *DeviceAuthenticationPolicyCommonFido2Failure
	isSet bool
}

func (v NullableDeviceAuthenticationPolicyCommonFido2Failure) Get() *DeviceAuthenticationPolicyCommonFido2Failure {
	return v.value
}

func (v *NullableDeviceAuthenticationPolicyCommonFido2Failure) Set(val *DeviceAuthenticationPolicyCommonFido2Failure) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceAuthenticationPolicyCommonFido2Failure) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceAuthenticationPolicyCommonFido2Failure) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceAuthenticationPolicyCommonFido2Failure(val *DeviceAuthenticationPolicyCommonFido2Failure) *NullableDeviceAuthenticationPolicyCommonFido2Failure {
	return &NullableDeviceAuthenticationPolicyCommonFido2Failure{value: val, isSet: true}
}

func (v NullableDeviceAuthenticationPolicyCommonFido2Failure) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceAuthenticationPolicyCommonFido2Failure) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
