/*
PingOne Platform API - PingOne MFA

The PingOne Platform API covering the PingOne MFA service

API version: 2023-06-29
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mfa

import (
	"encoding/json"
)

// checks if the ReadDeviceAuthenticationPolicies200ResponseEmbedded type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReadDeviceAuthenticationPolicies200ResponseEmbedded{}

// ReadDeviceAuthenticationPolicies200ResponseEmbedded struct for ReadDeviceAuthenticationPolicies200ResponseEmbedded
type ReadDeviceAuthenticationPolicies200ResponseEmbedded struct {
	DeviceAuthenticationPolicies []DeviceAuthenticationPolicy `json:"deviceAuthenticationPolicies,omitempty"`
}

// NewReadDeviceAuthenticationPolicies200ResponseEmbedded instantiates a new ReadDeviceAuthenticationPolicies200ResponseEmbedded object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReadDeviceAuthenticationPolicies200ResponseEmbedded() *ReadDeviceAuthenticationPolicies200ResponseEmbedded {
	this := ReadDeviceAuthenticationPolicies200ResponseEmbedded{}
	return &this
}

// NewReadDeviceAuthenticationPolicies200ResponseEmbeddedWithDefaults instantiates a new ReadDeviceAuthenticationPolicies200ResponseEmbedded object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReadDeviceAuthenticationPolicies200ResponseEmbeddedWithDefaults() *ReadDeviceAuthenticationPolicies200ResponseEmbedded {
	this := ReadDeviceAuthenticationPolicies200ResponseEmbedded{}
	return &this
}

// GetDeviceAuthenticationPolicies returns the DeviceAuthenticationPolicies field value if set, zero value otherwise.
func (o *ReadDeviceAuthenticationPolicies200ResponseEmbedded) GetDeviceAuthenticationPolicies() []DeviceAuthenticationPolicy {
	if o == nil || IsNil(o.DeviceAuthenticationPolicies) {
		var ret []DeviceAuthenticationPolicy
		return ret
	}
	return o.DeviceAuthenticationPolicies
}

// GetDeviceAuthenticationPoliciesOk returns a tuple with the DeviceAuthenticationPolicies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReadDeviceAuthenticationPolicies200ResponseEmbedded) GetDeviceAuthenticationPoliciesOk() ([]DeviceAuthenticationPolicy, bool) {
	if o == nil || IsNil(o.DeviceAuthenticationPolicies) {
		return nil, false
	}
	return o.DeviceAuthenticationPolicies, true
}

// HasDeviceAuthenticationPolicies returns a boolean if a field has been set.
func (o *ReadDeviceAuthenticationPolicies200ResponseEmbedded) HasDeviceAuthenticationPolicies() bool {
	if o != nil && !IsNil(o.DeviceAuthenticationPolicies) {
		return true
	}

	return false
}

// SetDeviceAuthenticationPolicies gets a reference to the given []DeviceAuthenticationPolicy and assigns it to the DeviceAuthenticationPolicies field.
func (o *ReadDeviceAuthenticationPolicies200ResponseEmbedded) SetDeviceAuthenticationPolicies(v []DeviceAuthenticationPolicy) {
	o.DeviceAuthenticationPolicies = v
}

func (o ReadDeviceAuthenticationPolicies200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReadDeviceAuthenticationPolicies200ResponseEmbedded) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeviceAuthenticationPolicies) {
		toSerialize["deviceAuthenticationPolicies"] = o.DeviceAuthenticationPolicies
	}
	return toSerialize, nil
}

type NullableReadDeviceAuthenticationPolicies200ResponseEmbedded struct {
	value *ReadDeviceAuthenticationPolicies200ResponseEmbedded
	isSet bool
}

func (v NullableReadDeviceAuthenticationPolicies200ResponseEmbedded) Get() *ReadDeviceAuthenticationPolicies200ResponseEmbedded {
	return v.value
}

func (v *NullableReadDeviceAuthenticationPolicies200ResponseEmbedded) Set(val *ReadDeviceAuthenticationPolicies200ResponseEmbedded) {
	v.value = val
	v.isSet = true
}

func (v NullableReadDeviceAuthenticationPolicies200ResponseEmbedded) IsSet() bool {
	return v.isSet
}

func (v *NullableReadDeviceAuthenticationPolicies200ResponseEmbedded) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReadDeviceAuthenticationPolicies200ResponseEmbedded(val *ReadDeviceAuthenticationPolicies200ResponseEmbedded) *NullableReadDeviceAuthenticationPolicies200ResponseEmbedded {
	return &NullableReadDeviceAuthenticationPolicies200ResponseEmbedded{value: val, isSet: true}
}

func (v NullableReadDeviceAuthenticationPolicies200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReadDeviceAuthenticationPolicies200ResponseEmbedded) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


