/*
PingOne Platform API - PingOne MFA

The PingOne Platform API covering the PingOne MFA service

API version: 2023-06-29
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mfa

import (
	"encoding/json"
)

// checks if the DeviceAuthenticationPolicyOathTokenPairingKeyLifetime type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceAuthenticationPolicyOathTokenPairingKeyLifetime{}

// DeviceAuthenticationPolicyOathTokenPairingKeyLifetime struct for DeviceAuthenticationPolicyOathTokenPairingKeyLifetime
type DeviceAuthenticationPolicyOathTokenPairingKeyLifetime struct {
	// For \"desktop\" only. The amount of time the pairing key is valid. Can be expressed in minutes or hours. Minimum is one minute, maximum is 48 hours. If the `pairingKeyLifetime` object is not provided, then 48 hours is used.
	Duration int32        `json:"duration"`
	TimeUnit EnumTimeUnit `json:"timeUnit"`
}

// NewDeviceAuthenticationPolicyOathTokenPairingKeyLifetime instantiates a new DeviceAuthenticationPolicyOathTokenPairingKeyLifetime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceAuthenticationPolicyOathTokenPairingKeyLifetime(duration int32, timeUnit EnumTimeUnit) *DeviceAuthenticationPolicyOathTokenPairingKeyLifetime {
	this := DeviceAuthenticationPolicyOathTokenPairingKeyLifetime{}
	this.Duration = duration
	this.TimeUnit = timeUnit
	return &this
}

// NewDeviceAuthenticationPolicyOathTokenPairingKeyLifetimeWithDefaults instantiates a new DeviceAuthenticationPolicyOathTokenPairingKeyLifetime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceAuthenticationPolicyOathTokenPairingKeyLifetimeWithDefaults() *DeviceAuthenticationPolicyOathTokenPairingKeyLifetime {
	this := DeviceAuthenticationPolicyOathTokenPairingKeyLifetime{}
	return &this
}

// GetDuration returns the Duration field value
func (o *DeviceAuthenticationPolicyOathTokenPairingKeyLifetime) GetDuration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *DeviceAuthenticationPolicyOathTokenPairingKeyLifetime) GetDurationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *DeviceAuthenticationPolicyOathTokenPairingKeyLifetime) SetDuration(v int32) {
	o.Duration = v
}

// GetTimeUnit returns the TimeUnit field value
func (o *DeviceAuthenticationPolicyOathTokenPairingKeyLifetime) GetTimeUnit() EnumTimeUnit {
	if o == nil {
		var ret EnumTimeUnit
		return ret
	}

	return o.TimeUnit
}

// GetTimeUnitOk returns a tuple with the TimeUnit field value
// and a boolean to check if the value has been set.
func (o *DeviceAuthenticationPolicyOathTokenPairingKeyLifetime) GetTimeUnitOk() (*EnumTimeUnit, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeUnit, true
}

// SetTimeUnit sets field value
func (o *DeviceAuthenticationPolicyOathTokenPairingKeyLifetime) SetTimeUnit(v EnumTimeUnit) {
	o.TimeUnit = v
}

func (o DeviceAuthenticationPolicyOathTokenPairingKeyLifetime) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceAuthenticationPolicyOathTokenPairingKeyLifetime) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["duration"] = o.Duration
	toSerialize["timeUnit"] = o.TimeUnit
	return toSerialize, nil
}

type NullableDeviceAuthenticationPolicyOathTokenPairingKeyLifetime struct {
	value *DeviceAuthenticationPolicyOathTokenPairingKeyLifetime
	isSet bool
}

func (v NullableDeviceAuthenticationPolicyOathTokenPairingKeyLifetime) Get() *DeviceAuthenticationPolicyOathTokenPairingKeyLifetime {
	return v.value
}

func (v *NullableDeviceAuthenticationPolicyOathTokenPairingKeyLifetime) Set(val *DeviceAuthenticationPolicyOathTokenPairingKeyLifetime) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceAuthenticationPolicyOathTokenPairingKeyLifetime) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceAuthenticationPolicyOathTokenPairingKeyLifetime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceAuthenticationPolicyOathTokenPairingKeyLifetime(val *DeviceAuthenticationPolicyOathTokenPairingKeyLifetime) *NullableDeviceAuthenticationPolicyOathTokenPairingKeyLifetime {
	return &NullableDeviceAuthenticationPolicyOathTokenPairingKeyLifetime{value: val, isSet: true}
}

func (v NullableDeviceAuthenticationPolicyOathTokenPairingKeyLifetime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceAuthenticationPolicyOathTokenPairingKeyLifetime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
