/*
PingOne Platform API - PingOne MFA

The PingOne Platform API covering the PingOne MFA service

API version: 2023-06-29
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mfa

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DeviceAuthenticationPolicyMigrateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceAuthenticationPolicyMigrateData{}

// DeviceAuthenticationPolicyMigrateData struct for DeviceAuthenticationPolicyMigrateData
type DeviceAuthenticationPolicyMigrateData struct {
	// The ID of the device authentication policy.
	DeviceAuthenticationPolicyId string `json:"deviceAuthenticationPolicyId"`
	// The ID of the FIDO2 policy.
	Fido2PolicyId *string `json:"fido2PolicyId,omitempty"`
}

type _DeviceAuthenticationPolicyMigrateData DeviceAuthenticationPolicyMigrateData

// NewDeviceAuthenticationPolicyMigrateData instantiates a new DeviceAuthenticationPolicyMigrateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceAuthenticationPolicyMigrateData(deviceAuthenticationPolicyId string) *DeviceAuthenticationPolicyMigrateData {
	this := DeviceAuthenticationPolicyMigrateData{}
	this.DeviceAuthenticationPolicyId = deviceAuthenticationPolicyId
	return &this
}

// NewDeviceAuthenticationPolicyMigrateDataWithDefaults instantiates a new DeviceAuthenticationPolicyMigrateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceAuthenticationPolicyMigrateDataWithDefaults() *DeviceAuthenticationPolicyMigrateData {
	this := DeviceAuthenticationPolicyMigrateData{}
	return &this
}

// GetDeviceAuthenticationPolicyId returns the DeviceAuthenticationPolicyId field value
func (o *DeviceAuthenticationPolicyMigrateData) GetDeviceAuthenticationPolicyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceAuthenticationPolicyId
}

// GetDeviceAuthenticationPolicyIdOk returns a tuple with the DeviceAuthenticationPolicyId field value
// and a boolean to check if the value has been set.
func (o *DeviceAuthenticationPolicyMigrateData) GetDeviceAuthenticationPolicyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceAuthenticationPolicyId, true
}

// SetDeviceAuthenticationPolicyId sets field value
func (o *DeviceAuthenticationPolicyMigrateData) SetDeviceAuthenticationPolicyId(v string) {
	o.DeviceAuthenticationPolicyId = v
}

// GetFido2PolicyId returns the Fido2PolicyId field value if set, zero value otherwise.
func (o *DeviceAuthenticationPolicyMigrateData) GetFido2PolicyId() string {
	if o == nil || IsNil(o.Fido2PolicyId) {
		var ret string
		return ret
	}
	return *o.Fido2PolicyId
}

// GetFido2PolicyIdOk returns a tuple with the Fido2PolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceAuthenticationPolicyMigrateData) GetFido2PolicyIdOk() (*string, bool) {
	if o == nil || IsNil(o.Fido2PolicyId) {
		return nil, false
	}
	return o.Fido2PolicyId, true
}

// HasFido2PolicyId returns a boolean if a field has been set.
func (o *DeviceAuthenticationPolicyMigrateData) HasFido2PolicyId() bool {
	if o != nil && !IsNil(o.Fido2PolicyId) {
		return true
	}

	return false
}

// SetFido2PolicyId gets a reference to the given string and assigns it to the Fido2PolicyId field.
func (o *DeviceAuthenticationPolicyMigrateData) SetFido2PolicyId(v string) {
	o.Fido2PolicyId = &v
}

func (o DeviceAuthenticationPolicyMigrateData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceAuthenticationPolicyMigrateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deviceAuthenticationPolicyId"] = o.DeviceAuthenticationPolicyId
	if !IsNil(o.Fido2PolicyId) {
		toSerialize["fido2PolicyId"] = o.Fido2PolicyId
	}
	return toSerialize, nil
}

func (o *DeviceAuthenticationPolicyMigrateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deviceAuthenticationPolicyId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeviceAuthenticationPolicyMigrateData := _DeviceAuthenticationPolicyMigrateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeviceAuthenticationPolicyMigrateData)

	if err != nil {
		return err
	}

	*o = DeviceAuthenticationPolicyMigrateData(varDeviceAuthenticationPolicyMigrateData)

	return err
}

type NullableDeviceAuthenticationPolicyMigrateData struct {
	value *DeviceAuthenticationPolicyMigrateData
	isSet bool
}

func (v NullableDeviceAuthenticationPolicyMigrateData) Get() *DeviceAuthenticationPolicyMigrateData {
	return v.value
}

func (v *NullableDeviceAuthenticationPolicyMigrateData) Set(val *DeviceAuthenticationPolicyMigrateData) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceAuthenticationPolicyMigrateData) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceAuthenticationPolicyMigrateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceAuthenticationPolicyMigrateData(val *DeviceAuthenticationPolicyMigrateData) *NullableDeviceAuthenticationPolicyMigrateData {
	return &NullableDeviceAuthenticationPolicyMigrateData{value: val, isSet: true}
}

func (v NullableDeviceAuthenticationPolicyMigrateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceAuthenticationPolicyMigrateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
