/*
PingOne Platform API - SSO and Base

The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)

API version: 2022-08-02
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
)

// checks if the GatewayTypeRADIUSAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayTypeRADIUSAllOf{}

// GatewayTypeRADIUSAllOf struct for GatewayTypeRADIUSAllOf
type GatewayTypeRADIUSAllOf struct {
	Davinci GatewayTypeRADIUSAllOfDavinci `json:"davinci"`
	// Value to use for the shared secret if the shared secret is not provided for one or more of the RADIUS clients specified.
	DefaultSharedSecret *string `json:"defaultSharedSecret,omitempty"`
	// Collection of RADIUS clients.
	RadiusClients []GatewayTypeRADIUSAllOfRadiusClients `json:"radiusClients"`
}

// NewGatewayTypeRADIUSAllOf instantiates a new GatewayTypeRADIUSAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayTypeRADIUSAllOf(davinci GatewayTypeRADIUSAllOfDavinci, radiusClients []GatewayTypeRADIUSAllOfRadiusClients) *GatewayTypeRADIUSAllOf {
	this := GatewayTypeRADIUSAllOf{}
	this.Davinci = davinci
	this.RadiusClients = radiusClients
	return &this
}

// NewGatewayTypeRADIUSAllOfWithDefaults instantiates a new GatewayTypeRADIUSAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayTypeRADIUSAllOfWithDefaults() *GatewayTypeRADIUSAllOf {
	this := GatewayTypeRADIUSAllOf{}
	return &this
}

// GetDavinci returns the Davinci field value
func (o *GatewayTypeRADIUSAllOf) GetDavinci() GatewayTypeRADIUSAllOfDavinci {
	if o == nil {
		var ret GatewayTypeRADIUSAllOfDavinci
		return ret
	}

	return o.Davinci
}

// GetDavinciOk returns a tuple with the Davinci field value
// and a boolean to check if the value has been set.
func (o *GatewayTypeRADIUSAllOf) GetDavinciOk() (*GatewayTypeRADIUSAllOfDavinci, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Davinci, true
}

// SetDavinci sets field value
func (o *GatewayTypeRADIUSAllOf) SetDavinci(v GatewayTypeRADIUSAllOfDavinci) {
	o.Davinci = v
}

// GetDefaultSharedSecret returns the DefaultSharedSecret field value if set, zero value otherwise.
func (o *GatewayTypeRADIUSAllOf) GetDefaultSharedSecret() string {
	if o == nil || IsNil(o.DefaultSharedSecret) {
		var ret string
		return ret
	}
	return *o.DefaultSharedSecret
}

// GetDefaultSharedSecretOk returns a tuple with the DefaultSharedSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayTypeRADIUSAllOf) GetDefaultSharedSecretOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultSharedSecret) {
		return nil, false
	}
	return o.DefaultSharedSecret, true
}

// HasDefaultSharedSecret returns a boolean if a field has been set.
func (o *GatewayTypeRADIUSAllOf) HasDefaultSharedSecret() bool {
	if o != nil && !IsNil(o.DefaultSharedSecret) {
		return true
	}

	return false
}

// SetDefaultSharedSecret gets a reference to the given string and assigns it to the DefaultSharedSecret field.
func (o *GatewayTypeRADIUSAllOf) SetDefaultSharedSecret(v string) {
	o.DefaultSharedSecret = &v
}

// GetRadiusClients returns the RadiusClients field value
func (o *GatewayTypeRADIUSAllOf) GetRadiusClients() []GatewayTypeRADIUSAllOfRadiusClients {
	if o == nil {
		var ret []GatewayTypeRADIUSAllOfRadiusClients
		return ret
	}

	return o.RadiusClients
}

// GetRadiusClientsOk returns a tuple with the RadiusClients field value
// and a boolean to check if the value has been set.
func (o *GatewayTypeRADIUSAllOf) GetRadiusClientsOk() ([]GatewayTypeRADIUSAllOfRadiusClients, bool) {
	if o == nil {
		return nil, false
	}
	return o.RadiusClients, true
}

// SetRadiusClients sets field value
func (o *GatewayTypeRADIUSAllOf) SetRadiusClients(v []GatewayTypeRADIUSAllOfRadiusClients) {
	o.RadiusClients = v
}

func (o GatewayTypeRADIUSAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayTypeRADIUSAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["davinci"] = o.Davinci
	if !IsNil(o.DefaultSharedSecret) {
		toSerialize["defaultSharedSecret"] = o.DefaultSharedSecret
	}
	toSerialize["radiusClients"] = o.RadiusClients
	return toSerialize, nil
}

type NullableGatewayTypeRADIUSAllOf struct {
	value *GatewayTypeRADIUSAllOf
	isSet bool
}

func (v NullableGatewayTypeRADIUSAllOf) Get() *GatewayTypeRADIUSAllOf {
	return v.value
}

func (v *NullableGatewayTypeRADIUSAllOf) Set(val *GatewayTypeRADIUSAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayTypeRADIUSAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayTypeRADIUSAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayTypeRADIUSAllOf(val *GatewayTypeRADIUSAllOf) *NullableGatewayTypeRADIUSAllOf {
	return &NullableGatewayTypeRADIUSAllOf{value: val, isSet: true}
}

func (v NullableGatewayTypeRADIUSAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayTypeRADIUSAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


