/*
PingOne Platform API - SSO and Base

The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)

API version: 2023-06-29
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
)

// checks if the TopLevelLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TopLevelLinks{}

// TopLevelLinks struct for TopLevelLinks
type TopLevelLinks struct {
	Self *TopLevelLinksSelf `json:"self,omitempty"`
	Next *TopLevelLinksNext `json:"next,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TopLevelLinks TopLevelLinks

// NewTopLevelLinks instantiates a new TopLevelLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTopLevelLinks() *TopLevelLinks {
	this := TopLevelLinks{}
	return &this
}

// NewTopLevelLinksWithDefaults instantiates a new TopLevelLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTopLevelLinksWithDefaults() *TopLevelLinks {
	this := TopLevelLinks{}
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *TopLevelLinks) GetSelf() TopLevelLinksSelf {
	if o == nil || IsNil(o.Self) {
		var ret TopLevelLinksSelf
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopLevelLinks) GetSelfOk() (*TopLevelLinksSelf, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *TopLevelLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given TopLevelLinksSelf and assigns it to the Self field.
func (o *TopLevelLinks) SetSelf(v TopLevelLinksSelf) {
	o.Self = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *TopLevelLinks) GetNext() TopLevelLinksNext {
	if o == nil || IsNil(o.Next) {
		var ret TopLevelLinksNext
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopLevelLinks) GetNextOk() (*TopLevelLinksNext, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *TopLevelLinks) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given TopLevelLinksNext and assigns it to the Next field.
func (o *TopLevelLinks) SetNext(v TopLevelLinksNext) {
	o.Next = &v
}

func (o TopLevelLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TopLevelLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TopLevelLinks) UnmarshalJSON(bytes []byte) (err error) {
	varTopLevelLinks := _TopLevelLinks{}

	if err = json.Unmarshal(bytes, &varTopLevelLinks); err == nil {
		*o = TopLevelLinks(varTopLevelLinks)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "self")
		delete(additionalProperties, "next")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTopLevelLinks struct {
	value *TopLevelLinks
	isSet bool
}

func (v NullableTopLevelLinks) Get() *TopLevelLinks {
	return v.value
}

func (v *NullableTopLevelLinks) Set(val *TopLevelLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableTopLevelLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableTopLevelLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTopLevelLinks(val *TopLevelLinks) *NullableTopLevelLinks {
	return &NullableTopLevelLinks{value: val, isSet: true}
}

func (v NullableTopLevelLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTopLevelLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


