/*
PingOne Platform API - SSO and Base

The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)

API version: 2022-08-02
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
	"fmt"
)

// EnumFormQrCodeAlignment A string that specifies the QR Code alignment. Options are LEFT, RIGHT, and CENTER.
type EnumFormQrCodeAlignment string

// List of EnumFormQrCodeAlignment
const (
	ENUMFORMQRCODEALIGNMENT_LEFT EnumFormQrCodeAlignment = "LEFT"
	ENUMFORMQRCODEALIGNMENT_RIGHT EnumFormQrCodeAlignment = "RIGHT"
	ENUMFORMQRCODEALIGNMENT_CENTER EnumFormQrCodeAlignment = "CENTER"
)

// All allowed values of EnumFormQrCodeAlignment enum
var AllowedEnumFormQrCodeAlignmentEnumValues = []EnumFormQrCodeAlignment{
	"LEFT",
	"RIGHT",
	"CENTER",
}

func (v *EnumFormQrCodeAlignment) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EnumFormQrCodeAlignment(value)
	for _, existing := range AllowedEnumFormQrCodeAlignmentEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EnumFormQrCodeAlignment", value)
}

// NewEnumFormQrCodeAlignmentFromValue returns a pointer to a valid EnumFormQrCodeAlignment
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEnumFormQrCodeAlignmentFromValue(v string) (*EnumFormQrCodeAlignment, error) {
	ev := EnumFormQrCodeAlignment(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EnumFormQrCodeAlignment: valid values are %v", v, AllowedEnumFormQrCodeAlignmentEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EnumFormQrCodeAlignment) IsValid() bool {
	for _, existing := range AllowedEnumFormQrCodeAlignmentEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EnumFormQrCodeAlignment value
func (v EnumFormQrCodeAlignment) Ptr() *EnumFormQrCodeAlignment {
	return &v
}

type NullableEnumFormQrCodeAlignment struct {
	value *EnumFormQrCodeAlignment
	isSet bool
}

func (v NullableEnumFormQrCodeAlignment) Get() *EnumFormQrCodeAlignment {
	return v.value
}

func (v *NullableEnumFormQrCodeAlignment) Set(val *EnumFormQrCodeAlignment) {
	v.value = val
	v.isSet = true
}

func (v NullableEnumFormQrCodeAlignment) IsSet() bool {
	return v.isSet
}

func (v *NullableEnumFormQrCodeAlignment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnumFormQrCodeAlignment(val *EnumFormQrCodeAlignment) *NullableEnumFormQrCodeAlignment {
	return &NullableEnumFormQrCodeAlignment{value: val, isSet: true}
}

func (v NullableEnumFormQrCodeAlignment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnumFormQrCodeAlignment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

