/*
PingOne Platform API - SSO and Base

The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)

API version: 2022-08-02
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
)

// ApplicationPingOneAdminConsole struct for ApplicationPingOneAdminConsole
type ApplicationPingOneAdminConsole struct {
	PkceEnforcement *EnumApplicationOIDCPKCEOption `json:"pkceEnforcement,omitempty"`
	TokenEndpointAuthMethod *EnumApplicationOIDCTokenAuthMethod `json:"tokenEndpointAuthMethod,omitempty"`
}

// NewApplicationPingOneAdminConsole instantiates a new ApplicationPingOneAdminConsole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationPingOneAdminConsole() *ApplicationPingOneAdminConsole {
	this := ApplicationPingOneAdminConsole{}
	return &this
}

// NewApplicationPingOneAdminConsoleWithDefaults instantiates a new ApplicationPingOneAdminConsole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationPingOneAdminConsoleWithDefaults() *ApplicationPingOneAdminConsole {
	this := ApplicationPingOneAdminConsole{}
	return &this
}

// GetPkceEnforcement returns the PkceEnforcement field value if set, zero value otherwise.
func (o *ApplicationPingOneAdminConsole) GetPkceEnforcement() EnumApplicationOIDCPKCEOption {
	if o == nil || isNil(o.PkceEnforcement) {
		var ret EnumApplicationOIDCPKCEOption
		return ret
	}
	return *o.PkceEnforcement
}

// GetPkceEnforcementOk returns a tuple with the PkceEnforcement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationPingOneAdminConsole) GetPkceEnforcementOk() (*EnumApplicationOIDCPKCEOption, bool) {
	if o == nil || isNil(o.PkceEnforcement) {
    return nil, false
	}
	return o.PkceEnforcement, true
}

// HasPkceEnforcement returns a boolean if a field has been set.
func (o *ApplicationPingOneAdminConsole) HasPkceEnforcement() bool {
	if o != nil && !isNil(o.PkceEnforcement) {
		return true
	}

	return false
}

// SetPkceEnforcement gets a reference to the given EnumApplicationOIDCPKCEOption and assigns it to the PkceEnforcement field.
func (o *ApplicationPingOneAdminConsole) SetPkceEnforcement(v EnumApplicationOIDCPKCEOption) {
	o.PkceEnforcement = &v
}

// GetTokenEndpointAuthMethod returns the TokenEndpointAuthMethod field value if set, zero value otherwise.
func (o *ApplicationPingOneAdminConsole) GetTokenEndpointAuthMethod() EnumApplicationOIDCTokenAuthMethod {
	if o == nil || isNil(o.TokenEndpointAuthMethod) {
		var ret EnumApplicationOIDCTokenAuthMethod
		return ret
	}
	return *o.TokenEndpointAuthMethod
}

// GetTokenEndpointAuthMethodOk returns a tuple with the TokenEndpointAuthMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationPingOneAdminConsole) GetTokenEndpointAuthMethodOk() (*EnumApplicationOIDCTokenAuthMethod, bool) {
	if o == nil || isNil(o.TokenEndpointAuthMethod) {
    return nil, false
	}
	return o.TokenEndpointAuthMethod, true
}

// HasTokenEndpointAuthMethod returns a boolean if a field has been set.
func (o *ApplicationPingOneAdminConsole) HasTokenEndpointAuthMethod() bool {
	if o != nil && !isNil(o.TokenEndpointAuthMethod) {
		return true
	}

	return false
}

// SetTokenEndpointAuthMethod gets a reference to the given EnumApplicationOIDCTokenAuthMethod and assigns it to the TokenEndpointAuthMethod field.
func (o *ApplicationPingOneAdminConsole) SetTokenEndpointAuthMethod(v EnumApplicationOIDCTokenAuthMethod) {
	o.TokenEndpointAuthMethod = &v
}

func (o ApplicationPingOneAdminConsole) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.PkceEnforcement) {
		toSerialize["pkceEnforcement"] = o.PkceEnforcement
	}
	if !isNil(o.TokenEndpointAuthMethod) {
		toSerialize["tokenEndpointAuthMethod"] = o.TokenEndpointAuthMethod
	}
	return json.Marshal(toSerialize)
}

type NullableApplicationPingOneAdminConsole struct {
	value *ApplicationPingOneAdminConsole
	isSet bool
}

func (v NullableApplicationPingOneAdminConsole) Get() *ApplicationPingOneAdminConsole {
	return v.value
}

func (v *NullableApplicationPingOneAdminConsole) Set(val *ApplicationPingOneAdminConsole) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationPingOneAdminConsole) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationPingOneAdminConsole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationPingOneAdminConsole(val *ApplicationPingOneAdminConsole) *NullableApplicationPingOneAdminConsole {
	return &NullableApplicationPingOneAdminConsole{value: val, isSet: true}
}

func (v NullableApplicationPingOneAdminConsole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationPingOneAdminConsole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


