/*
PingOne Platform API - SSO and Base

The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)

API version: 2022-07-18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
)

// IdentityProviderYahooAllOf struct for IdentityProviderYahooAllOf
type IdentityProviderYahooAllOf struct {
	// A string that specifies the application ID from Yahoo. This is a required property.
	ClientId string `json:"clientId"`
	// A string that specifies the application secret from Yahoo. This is a required property.
	ClientSecret string `json:"clientSecret"`
}

// NewIdentityProviderYahooAllOf instantiates a new IdentityProviderYahooAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentityProviderYahooAllOf(clientId string, clientSecret string) *IdentityProviderYahooAllOf {
	this := IdentityProviderYahooAllOf{}
	this.ClientId = clientId
	this.ClientSecret = clientSecret
	return &this
}

// NewIdentityProviderYahooAllOfWithDefaults instantiates a new IdentityProviderYahooAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentityProviderYahooAllOfWithDefaults() *IdentityProviderYahooAllOf {
	this := IdentityProviderYahooAllOf{}
	return &this
}

// GetClientId returns the ClientId field value
func (o *IdentityProviderYahooAllOf) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *IdentityProviderYahooAllOf) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *IdentityProviderYahooAllOf) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *IdentityProviderYahooAllOf) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *IdentityProviderYahooAllOf) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *IdentityProviderYahooAllOf) SetClientSecret(v string) {
	o.ClientSecret = v
}

func (o IdentityProviderYahooAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["clientId"] = o.ClientId
	}
	if true {
		toSerialize["clientSecret"] = o.ClientSecret
	}
	return json.Marshal(toSerialize)
}

type NullableIdentityProviderYahooAllOf struct {
	value *IdentityProviderYahooAllOf
	isSet bool
}

func (v NullableIdentityProviderYahooAllOf) Get() *IdentityProviderYahooAllOf {
	return v.value
}

func (v *NullableIdentityProviderYahooAllOf) Set(val *IdentityProviderYahooAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentityProviderYahooAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentityProviderYahooAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentityProviderYahooAllOf(val *IdentityProviderYahooAllOf) *NullableIdentityProviderYahooAllOf {
	return &NullableIdentityProviderYahooAllOf{value: val, isSet: true}
}

func (v NullableIdentityProviderYahooAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentityProviderYahooAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


