/*
PingOne Platform API - SSO and Base

The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)

API version: 2023-06-29
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
	"fmt"
)

// EnumPropagationStoreTypeRemoveActionDisable The action to take when deprovisioning (removing) a user. Must be set to Disable.
type EnumPropagationStoreTypeRemoveActionDisable string

// List of EnumPropagationStoreTypeRemoveActionDisable
const (
	ENUMPROPAGATIONSTORETYPEREMOVEACTIONDISABLE_DISABLE EnumPropagationStoreTypeRemoveActionDisable = "Disable"
)

// All allowed values of EnumPropagationStoreTypeRemoveActionDisable enum
var AllowedEnumPropagationStoreTypeRemoveActionDisableEnumValues = []EnumPropagationStoreTypeRemoveActionDisable{
	"Disable",
}

func (v *EnumPropagationStoreTypeRemoveActionDisable) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EnumPropagationStoreTypeRemoveActionDisable(value)
	for _, existing := range AllowedEnumPropagationStoreTypeRemoveActionDisableEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = EnumPropagationStoreTypeRemoveActionDisable(fmt.Sprintf("%s", "UNKNOWN"))
	return nil
}

// NewEnumPropagationStoreTypeRemoveActionDisableFromValue returns a pointer to a valid EnumPropagationStoreTypeRemoveActionDisable
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEnumPropagationStoreTypeRemoveActionDisableFromValue(v string) (*EnumPropagationStoreTypeRemoveActionDisable, error) {
	ev := EnumPropagationStoreTypeRemoveActionDisable(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EnumPropagationStoreTypeRemoveActionDisable: valid values are %v", v, AllowedEnumPropagationStoreTypeRemoveActionDisableEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EnumPropagationStoreTypeRemoveActionDisable) IsValid() bool {
	for _, existing := range AllowedEnumPropagationStoreTypeRemoveActionDisableEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EnumPropagationStoreTypeRemoveActionDisable value
func (v EnumPropagationStoreTypeRemoveActionDisable) Ptr() *EnumPropagationStoreTypeRemoveActionDisable {
	return &v
}

type NullableEnumPropagationStoreTypeRemoveActionDisable struct {
	value *EnumPropagationStoreTypeRemoveActionDisable
	isSet bool
}

func (v NullableEnumPropagationStoreTypeRemoveActionDisable) Get() *EnumPropagationStoreTypeRemoveActionDisable {
	return v.value
}

func (v *NullableEnumPropagationStoreTypeRemoveActionDisable) Set(val *EnumPropagationStoreTypeRemoveActionDisable) {
	v.value = val
	v.isSet = true
}

func (v NullableEnumPropagationStoreTypeRemoveActionDisable) IsSet() bool {
	return v.isSet
}

func (v *NullableEnumPropagationStoreTypeRemoveActionDisable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnumPropagationStoreTypeRemoveActionDisable(val *EnumPropagationStoreTypeRemoveActionDisable) *NullableEnumPropagationStoreTypeRemoveActionDisable {
	return &NullableEnumPropagationStoreTypeRemoveActionDisable{value: val, isSet: true}
}

func (v NullableEnumPropagationStoreTypeRemoveActionDisable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnumPropagationStoreTypeRemoveActionDisable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
