/*
PingOne Platform API - SSO and Base

The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)

API version: 2023-06-29
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
	"fmt"
)

// EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods the model 'EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods'
type EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods string

// List of EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods
const (
	ENUMNOTIFICATIONSPOLICYPROVIDERCONFIGURATIONCONDITIONSDELIVERYMETHODS_VOICE EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods = "VOICE"
	ENUMNOTIFICATIONSPOLICYPROVIDERCONFIGURATIONCONDITIONSDELIVERYMETHODS_SMS   EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods = "SMS"
)

// All allowed values of EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods enum
var AllowedEnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethodsEnumValues = []EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods{
	"VOICE",
	"SMS",
}

func (v *EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods(value)
	for _, existing := range AllowedEnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethodsEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods(fmt.Sprintf("%s", "UNKNOWN"))
	return nil
}

// NewEnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethodsFromValue returns a pointer to a valid EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethodsFromValue(v string) (*EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods, error) {
	ev := EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods: valid values are %v", v, AllowedEnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethodsEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods) IsValid() bool {
	for _, existing := range AllowedEnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethodsEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods value
func (v EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods) Ptr() *EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods {
	return &v
}

type NullableEnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods struct {
	value *EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods
	isSet bool
}

func (v NullableEnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods) Get() *EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods {
	return v.value
}

func (v *NullableEnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods) Set(val *EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods) {
	v.value = val
	v.isSet = true
}

func (v NullableEnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods) IsSet() bool {
	return v.isSet
}

func (v *NullableEnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods(val *EnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods) *NullableEnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods {
	return &NullableEnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods{value: val, isSet: true}
}

func (v NullableEnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnumNotificationsPolicyProviderConfigurationConditionsDeliveryMethods) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
