/*
PingOne Platform API - Authorize

The PingOne Platform API covering the PingOne Authorize service

API version: 2023-06-29
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authorize

import (
	"encoding/json"
)

// checks if the ApplicationRolePermissionResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationRolePermissionResource{}

// ApplicationRolePermissionResource struct for ApplicationRolePermissionResource
type ApplicationRolePermissionResource struct {
	// The ID of the application resource associated with this permission.
	Id *string `json:"id,omitempty"`
	// The name of the applicawtion resource associated with this permission.
	Name *string `json:"name,omitempty"`
}

// NewApplicationRolePermissionResource instantiates a new ApplicationRolePermissionResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationRolePermissionResource() *ApplicationRolePermissionResource {
	this := ApplicationRolePermissionResource{}
	return &this
}

// NewApplicationRolePermissionResourceWithDefaults instantiates a new ApplicationRolePermissionResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationRolePermissionResourceWithDefaults() *ApplicationRolePermissionResource {
	this := ApplicationRolePermissionResource{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApplicationRolePermissionResource) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationRolePermissionResource) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApplicationRolePermissionResource) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApplicationRolePermissionResource) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApplicationRolePermissionResource) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationRolePermissionResource) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApplicationRolePermissionResource) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApplicationRolePermissionResource) SetName(v string) {
	o.Name = &v
}

func (o ApplicationRolePermissionResource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationRolePermissionResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableApplicationRolePermissionResource struct {
	value *ApplicationRolePermissionResource
	isSet bool
}

func (v NullableApplicationRolePermissionResource) Get() *ApplicationRolePermissionResource {
	return v.value
}

func (v *NullableApplicationRolePermissionResource) Set(val *ApplicationRolePermissionResource) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationRolePermissionResource) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationRolePermissionResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationRolePermissionResource(val *ApplicationRolePermissionResource) *NullableApplicationRolePermissionResource {
	return &NullableApplicationRolePermissionResource{value: val, isSet: true}
}

func (v NullableApplicationRolePermissionResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationRolePermissionResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
