/*
PingOne Platform API - Authorize

The PingOne Platform API covering the PingOne Authorize service

API version: 2023-06-29
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authorize

import (
	"encoding/json"
)

// checks if the AuthorizeEditorDataValueTypeDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorizeEditorDataValueTypeDTO{}

// AuthorizeEditorDataValueTypeDTO struct for AuthorizeEditorDataValueTypeDTO
type AuthorizeEditorDataValueTypeDTO struct {
	Type EnumAuthorizeEditorDataValueTypeDTO `json:"type"`
}

// NewAuthorizeEditorDataValueTypeDTO instantiates a new AuthorizeEditorDataValueTypeDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizeEditorDataValueTypeDTO(type_ EnumAuthorizeEditorDataValueTypeDTO) *AuthorizeEditorDataValueTypeDTO {
	this := AuthorizeEditorDataValueTypeDTO{}
	this.Type = type_
	return &this
}

// NewAuthorizeEditorDataValueTypeDTOWithDefaults instantiates a new AuthorizeEditorDataValueTypeDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizeEditorDataValueTypeDTOWithDefaults() *AuthorizeEditorDataValueTypeDTO {
	this := AuthorizeEditorDataValueTypeDTO{}
	return &this
}

// GetType returns the Type field value
func (o *AuthorizeEditorDataValueTypeDTO) GetType() EnumAuthorizeEditorDataValueTypeDTO {
	if o == nil {
		var ret EnumAuthorizeEditorDataValueTypeDTO
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AuthorizeEditorDataValueTypeDTO) GetTypeOk() (*EnumAuthorizeEditorDataValueTypeDTO, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AuthorizeEditorDataValueTypeDTO) SetType(v EnumAuthorizeEditorDataValueTypeDTO) {
	o.Type = v
}

func (o AuthorizeEditorDataValueTypeDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorizeEditorDataValueTypeDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableAuthorizeEditorDataValueTypeDTO struct {
	value *AuthorizeEditorDataValueTypeDTO
	isSet bool
}

func (v NullableAuthorizeEditorDataValueTypeDTO) Get() *AuthorizeEditorDataValueTypeDTO {
	return v.value
}

func (v *NullableAuthorizeEditorDataValueTypeDTO) Set(val *AuthorizeEditorDataValueTypeDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizeEditorDataValueTypeDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizeEditorDataValueTypeDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizeEditorDataValueTypeDTO(val *AuthorizeEditorDataValueTypeDTO) *NullableAuthorizeEditorDataValueTypeDTO {
	return &NullableAuthorizeEditorDataValueTypeDTO{value: val, isSet: true}
}

func (v NullableAuthorizeEditorDataValueTypeDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizeEditorDataValueTypeDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


