/*
PingOne Platform API - Authorize

The PingOne Platform API covering the PingOne Authorize service

API version: 2023-06-29
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authorize

import (
	"encoding/json"
)

// checks if the AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO{}

// AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO struct for AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO
type AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO struct {
	Type EnumAuthorizeEditorDataRulesEffectSettingsDTOType `json:"type"`
}

// NewAuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO instantiates a new AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO(type_ EnumAuthorizeEditorDataRulesEffectSettingsDTOType) *AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO {
	this := AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO{}
	this.Type = type_
	return &this
}

// NewAuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTOWithDefaults instantiates a new AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTOWithDefaults() *AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO {
	this := AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO{}
	return &this
}

// GetType returns the Type field value
func (o *AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO) GetType() EnumAuthorizeEditorDataRulesEffectSettingsDTOType {
	if o == nil {
		var ret EnumAuthorizeEditorDataRulesEffectSettingsDTOType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO) GetTypeOk() (*EnumAuthorizeEditorDataRulesEffectSettingsDTOType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO) SetType(v EnumAuthorizeEditorDataRulesEffectSettingsDTOType) {
	o.Type = v
}

func (o AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableAuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO struct {
	value *AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO
	isSet bool
}

func (v NullableAuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO) Get() *AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO {
	return v.value
}

func (v *NullableAuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO) Set(val *AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO(val *AuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO) *NullableAuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO {
	return &NullableAuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO{value: val, isSet: true}
}

func (v NullableAuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizeEditorDataRulesEffectSettingsUnconditionalPermitDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


