/*
PingOne Platform API - Authorize

The PingOne Platform API covering the PingOne Authorize service

API version: 2023-06-29
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authorize

import (
	"encoding/json"
	"fmt"
)

// CreateServiceRequest - The service to create, without ID or Version properties
type CreateServiceRequest struct {
	AuthorizeEditorDataServicesConnectorServiceDefinitionDTO *AuthorizeEditorDataServicesConnectorServiceDefinitionDTO
	AuthorizeEditorDataServicesHttpServiceDefinitionDTO *AuthorizeEditorDataServicesHttpServiceDefinitionDTO
	AuthorizeEditorDataServicesNoneServiceDefinitionDTO *AuthorizeEditorDataServicesNoneServiceDefinitionDTO
}

// AuthorizeEditorDataServicesConnectorServiceDefinitionDTOAsCreateServiceRequest is a convenience function that returns AuthorizeEditorDataServicesConnectorServiceDefinitionDTO wrapped in CreateServiceRequest
func AuthorizeEditorDataServicesConnectorServiceDefinitionDTOAsCreateServiceRequest(v *AuthorizeEditorDataServicesConnectorServiceDefinitionDTO) CreateServiceRequest {
	return CreateServiceRequest{
		AuthorizeEditorDataServicesConnectorServiceDefinitionDTO: v,
	}
}

// AuthorizeEditorDataServicesHttpServiceDefinitionDTOAsCreateServiceRequest is a convenience function that returns AuthorizeEditorDataServicesHttpServiceDefinitionDTO wrapped in CreateServiceRequest
func AuthorizeEditorDataServicesHttpServiceDefinitionDTOAsCreateServiceRequest(v *AuthorizeEditorDataServicesHttpServiceDefinitionDTO) CreateServiceRequest {
	return CreateServiceRequest{
		AuthorizeEditorDataServicesHttpServiceDefinitionDTO: v,
	}
}

// AuthorizeEditorDataServicesNoneServiceDefinitionDTOAsCreateServiceRequest is a convenience function that returns AuthorizeEditorDataServicesNoneServiceDefinitionDTO wrapped in CreateServiceRequest
func AuthorizeEditorDataServicesNoneServiceDefinitionDTOAsCreateServiceRequest(v *AuthorizeEditorDataServicesNoneServiceDefinitionDTO) CreateServiceRequest {
	return CreateServiceRequest{
		AuthorizeEditorDataServicesNoneServiceDefinitionDTO: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CreateServiceRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AuthorizeEditorDataServicesConnectorServiceDefinitionDTO
	err = newStrictDecoder(data).Decode(&dst.AuthorizeEditorDataServicesConnectorServiceDefinitionDTO)
	if err == nil {
		jsonAuthorizeEditorDataServicesConnectorServiceDefinitionDTO, _ := json.Marshal(dst.AuthorizeEditorDataServicesConnectorServiceDefinitionDTO)
		if string(jsonAuthorizeEditorDataServicesConnectorServiceDefinitionDTO) == "{}" { // empty struct
			dst.AuthorizeEditorDataServicesConnectorServiceDefinitionDTO = nil
		} else {
			match++
		}
	} else {
		dst.AuthorizeEditorDataServicesConnectorServiceDefinitionDTO = nil
	}

	// try to unmarshal data into AuthorizeEditorDataServicesHttpServiceDefinitionDTO
	err = newStrictDecoder(data).Decode(&dst.AuthorizeEditorDataServicesHttpServiceDefinitionDTO)
	if err == nil {
		jsonAuthorizeEditorDataServicesHttpServiceDefinitionDTO, _ := json.Marshal(dst.AuthorizeEditorDataServicesHttpServiceDefinitionDTO)
		if string(jsonAuthorizeEditorDataServicesHttpServiceDefinitionDTO) == "{}" { // empty struct
			dst.AuthorizeEditorDataServicesHttpServiceDefinitionDTO = nil
		} else {
			match++
		}
	} else {
		dst.AuthorizeEditorDataServicesHttpServiceDefinitionDTO = nil
	}

	// try to unmarshal data into AuthorizeEditorDataServicesNoneServiceDefinitionDTO
	err = newStrictDecoder(data).Decode(&dst.AuthorizeEditorDataServicesNoneServiceDefinitionDTO)
	if err == nil {
		jsonAuthorizeEditorDataServicesNoneServiceDefinitionDTO, _ := json.Marshal(dst.AuthorizeEditorDataServicesNoneServiceDefinitionDTO)
		if string(jsonAuthorizeEditorDataServicesNoneServiceDefinitionDTO) == "{}" { // empty struct
			dst.AuthorizeEditorDataServicesNoneServiceDefinitionDTO = nil
		} else {
			match++
		}
	} else {
		dst.AuthorizeEditorDataServicesNoneServiceDefinitionDTO = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AuthorizeEditorDataServicesConnectorServiceDefinitionDTO = nil
		dst.AuthorizeEditorDataServicesHttpServiceDefinitionDTO = nil
		dst.AuthorizeEditorDataServicesNoneServiceDefinitionDTO = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CreateServiceRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CreateServiceRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateServiceRequest) MarshalJSON() ([]byte, error) {
	if src.AuthorizeEditorDataServicesConnectorServiceDefinitionDTO != nil {
		return json.Marshal(&src.AuthorizeEditorDataServicesConnectorServiceDefinitionDTO)
	}

	if src.AuthorizeEditorDataServicesHttpServiceDefinitionDTO != nil {
		return json.Marshal(&src.AuthorizeEditorDataServicesHttpServiceDefinitionDTO)
	}

	if src.AuthorizeEditorDataServicesNoneServiceDefinitionDTO != nil {
		return json.Marshal(&src.AuthorizeEditorDataServicesNoneServiceDefinitionDTO)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CreateServiceRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AuthorizeEditorDataServicesConnectorServiceDefinitionDTO != nil {
		return obj.AuthorizeEditorDataServicesConnectorServiceDefinitionDTO
	}

	if obj.AuthorizeEditorDataServicesHttpServiceDefinitionDTO != nil {
		return obj.AuthorizeEditorDataServicesHttpServiceDefinitionDTO
	}

	if obj.AuthorizeEditorDataServicesNoneServiceDefinitionDTO != nil {
		return obj.AuthorizeEditorDataServicesNoneServiceDefinitionDTO
	}

	// all schemas are nil
	return nil
}

type NullableCreateServiceRequest struct {
	value *CreateServiceRequest
	isSet bool
}

func (v NullableCreateServiceRequest) Get() *CreateServiceRequest {
	return v.value
}

func (v *NullableCreateServiceRequest) Set(val *CreateServiceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateServiceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateServiceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateServiceRequest(val *CreateServiceRequest) *NullableCreateServiceRequest {
	return &NullableCreateServiceRequest{value: val, isSet: true}
}

func (v NullableCreateServiceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateServiceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


