/*
PingOne Platform API - Authorize

The PingOne Platform API covering the PingOne Authorize service

API version: 2023-06-29
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authorize

import (
	"encoding/json"
)

// checks if the ListProcessors200ResponseEmbedded type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListProcessors200ResponseEmbedded{}

// ListProcessors200ResponseEmbedded struct for ListProcessors200ResponseEmbedded
type ListProcessors200ResponseEmbedded struct {
	AuthorizationProcessors []AuthorizeEditorDataDefinitionsProcessorDefinitionDTO `json:"authorizationProcessors,omitempty"`
}

// NewListProcessors200ResponseEmbedded instantiates a new ListProcessors200ResponseEmbedded object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListProcessors200ResponseEmbedded() *ListProcessors200ResponseEmbedded {
	this := ListProcessors200ResponseEmbedded{}
	return &this
}

// NewListProcessors200ResponseEmbeddedWithDefaults instantiates a new ListProcessors200ResponseEmbedded object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListProcessors200ResponseEmbeddedWithDefaults() *ListProcessors200ResponseEmbedded {
	this := ListProcessors200ResponseEmbedded{}
	return &this
}

// GetAuthorizationProcessors returns the AuthorizationProcessors field value if set, zero value otherwise.
func (o *ListProcessors200ResponseEmbedded) GetAuthorizationProcessors() []AuthorizeEditorDataDefinitionsProcessorDefinitionDTO {
	if o == nil || IsNil(o.AuthorizationProcessors) {
		var ret []AuthorizeEditorDataDefinitionsProcessorDefinitionDTO
		return ret
	}
	return o.AuthorizationProcessors
}

// GetAuthorizationProcessorsOk returns a tuple with the AuthorizationProcessors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProcessors200ResponseEmbedded) GetAuthorizationProcessorsOk() ([]AuthorizeEditorDataDefinitionsProcessorDefinitionDTO, bool) {
	if o == nil || IsNil(o.AuthorizationProcessors) {
		return nil, false
	}
	return o.AuthorizationProcessors, true
}

// HasAuthorizationProcessors returns a boolean if a field has been set.
func (o *ListProcessors200ResponseEmbedded) HasAuthorizationProcessors() bool {
	if o != nil && !IsNil(o.AuthorizationProcessors) {
		return true
	}

	return false
}

// SetAuthorizationProcessors gets a reference to the given []AuthorizeEditorDataDefinitionsProcessorDefinitionDTO and assigns it to the AuthorizationProcessors field.
func (o *ListProcessors200ResponseEmbedded) SetAuthorizationProcessors(v []AuthorizeEditorDataDefinitionsProcessorDefinitionDTO) {
	o.AuthorizationProcessors = v
}

func (o ListProcessors200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListProcessors200ResponseEmbedded) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthorizationProcessors) {
		toSerialize["authorizationProcessors"] = o.AuthorizationProcessors
	}
	return toSerialize, nil
}

type NullableListProcessors200ResponseEmbedded struct {
	value *ListProcessors200ResponseEmbedded
	isSet bool
}

func (v NullableListProcessors200ResponseEmbedded) Get() *ListProcessors200ResponseEmbedded {
	return v.value
}

func (v *NullableListProcessors200ResponseEmbedded) Set(val *ListProcessors200ResponseEmbedded) {
	v.value = val
	v.isSet = true
}

func (v NullableListProcessors200ResponseEmbedded) IsSet() bool {
	return v.isSet
}

func (v *NullableListProcessors200ResponseEmbedded) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListProcessors200ResponseEmbedded(val *ListProcessors200ResponseEmbedded) *NullableListProcessors200ResponseEmbedded {
	return &NullableListProcessors200ResponseEmbedded{value: val, isSet: true}
}

func (v NullableListProcessors200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListProcessors200ResponseEmbedded) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


