/*
PingOne Platform API - Authorize

The PingOne Platform API covering the PingOne Authorize service

API version: 2023-06-29
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authorize

import (
	"encoding/json"
)

// checks if the AuthorizeEditorDataTagRequestDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorizeEditorDataTagRequestDTO{}

// AuthorizeEditorDataTagRequestDTO The tag to create or update.
type AuthorizeEditorDataTagRequestDTO struct {
	Description *string `json:"description,omitempty"`
}

// NewAuthorizeEditorDataTagRequestDTO instantiates a new AuthorizeEditorDataTagRequestDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizeEditorDataTagRequestDTO() *AuthorizeEditorDataTagRequestDTO {
	this := AuthorizeEditorDataTagRequestDTO{}
	return &this
}

// NewAuthorizeEditorDataTagRequestDTOWithDefaults instantiates a new AuthorizeEditorDataTagRequestDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizeEditorDataTagRequestDTOWithDefaults() *AuthorizeEditorDataTagRequestDTO {
	this := AuthorizeEditorDataTagRequestDTO{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AuthorizeEditorDataTagRequestDTO) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizeEditorDataTagRequestDTO) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AuthorizeEditorDataTagRequestDTO) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AuthorizeEditorDataTagRequestDTO) SetDescription(v string) {
	o.Description = &v
}

func (o AuthorizeEditorDataTagRequestDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorizeEditorDataTagRequestDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableAuthorizeEditorDataTagRequestDTO struct {
	value *AuthorizeEditorDataTagRequestDTO
	isSet bool
}

func (v NullableAuthorizeEditorDataTagRequestDTO) Get() *AuthorizeEditorDataTagRequestDTO {
	return v.value
}

func (v *NullableAuthorizeEditorDataTagRequestDTO) Set(val *AuthorizeEditorDataTagRequestDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizeEditorDataTagRequestDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizeEditorDataTagRequestDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizeEditorDataTagRequestDTO(val *AuthorizeEditorDataTagRequestDTO) *NullableAuthorizeEditorDataTagRequestDTO {
	return &NullableAuthorizeEditorDataTagRequestDTO{value: val, isSet: true}
}

func (v NullableAuthorizeEditorDataTagRequestDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizeEditorDataTagRequestDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


