/*
PingOne Platform API - PingOne Risk

The PingOne Platform API covering the PingOne Risk service

API version: 2023-06-29
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package risk

import (
	"encoding/json"
	"fmt"
)

// EnumRiskPolicySetTargetsConditionType Included in risk policy responses. For transaction types, value returned is `STRING_LIST`. For user groups, value returned is `GROUPS_INTERSECTION`. For applications, value returned is `STRING_LIST`.
type EnumRiskPolicySetTargetsConditionType string

// List of EnumRiskPolicySetTargetsConditionType
const (
	ENUMRISKPOLICYSETTARGETSCONDITIONTYPE_STRING_LIST         EnumRiskPolicySetTargetsConditionType = "STRING_LIST"
	ENUMRISKPOLICYSETTARGETSCONDITIONTYPE_GROUPS_INTERSECTION EnumRiskPolicySetTargetsConditionType = "GROUPS_INTERSECTION"
)

// All allowed values of EnumRiskPolicySetTargetsConditionType enum
var AllowedEnumRiskPolicySetTargetsConditionTypeEnumValues = []EnumRiskPolicySetTargetsConditionType{
	"STRING_LIST",
	"GROUPS_INTERSECTION",
}

func (v *EnumRiskPolicySetTargetsConditionType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EnumRiskPolicySetTargetsConditionType(value)
	for _, existing := range AllowedEnumRiskPolicySetTargetsConditionTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = EnumRiskPolicySetTargetsConditionType(fmt.Sprintf("%s", "UNKNOWN"))
	return nil
}

// NewEnumRiskPolicySetTargetsConditionTypeFromValue returns a pointer to a valid EnumRiskPolicySetTargetsConditionType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEnumRiskPolicySetTargetsConditionTypeFromValue(v string) (*EnumRiskPolicySetTargetsConditionType, error) {
	ev := EnumRiskPolicySetTargetsConditionType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EnumRiskPolicySetTargetsConditionType: valid values are %v", v, AllowedEnumRiskPolicySetTargetsConditionTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EnumRiskPolicySetTargetsConditionType) IsValid() bool {
	for _, existing := range AllowedEnumRiskPolicySetTargetsConditionTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EnumRiskPolicySetTargetsConditionType value
func (v EnumRiskPolicySetTargetsConditionType) Ptr() *EnumRiskPolicySetTargetsConditionType {
	return &v
}

type NullableEnumRiskPolicySetTargetsConditionType struct {
	value *EnumRiskPolicySetTargetsConditionType
	isSet bool
}

func (v NullableEnumRiskPolicySetTargetsConditionType) Get() *EnumRiskPolicySetTargetsConditionType {
	return v.value
}

func (v *NullableEnumRiskPolicySetTargetsConditionType) Set(val *EnumRiskPolicySetTargetsConditionType) {
	v.value = val
	v.isSet = true
}

func (v NullableEnumRiskPolicySetTargetsConditionType) IsSet() bool {
	return v.isSet
}

func (v *NullableEnumRiskPolicySetTargetsConditionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnumRiskPolicySetTargetsConditionType(val *EnumRiskPolicySetTargetsConditionType) *NullableEnumRiskPolicySetTargetsConditionType {
	return &NullableEnumRiskPolicySetTargetsConditionType{value: val, isSet: true}
}

func (v NullableEnumRiskPolicySetTargetsConditionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnumRiskPolicySetTargetsConditionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
