/*
PingOne Platform API - PingOne Risk

The PingOne Platform API covering the PingOne Risk service

API version: 2023-06-29
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package risk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RiskPredictorCompositeAllOfComposition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskPredictorCompositeAllOfComposition{}

// RiskPredictorCompositeAllOfComposition struct for RiskPredictorCompositeAllOfComposition
type RiskPredictorCompositeAllOfComposition struct {
	Condition RiskPredictorCompositeConditionBase `json:"condition"`
	Level EnumRiskLevel `json:"level"`
}

type _RiskPredictorCompositeAllOfComposition RiskPredictorCompositeAllOfComposition

// NewRiskPredictorCompositeAllOfComposition instantiates a new RiskPredictorCompositeAllOfComposition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskPredictorCompositeAllOfComposition(condition RiskPredictorCompositeConditionBase, level EnumRiskLevel) *RiskPredictorCompositeAllOfComposition {
	this := RiskPredictorCompositeAllOfComposition{}
	this.Condition = condition
	this.Level = level
	return &this
}

// NewRiskPredictorCompositeAllOfCompositionWithDefaults instantiates a new RiskPredictorCompositeAllOfComposition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskPredictorCompositeAllOfCompositionWithDefaults() *RiskPredictorCompositeAllOfComposition {
	this := RiskPredictorCompositeAllOfComposition{}
	return &this
}

// GetCondition returns the Condition field value
func (o *RiskPredictorCompositeAllOfComposition) GetCondition() RiskPredictorCompositeConditionBase {
	if o == nil {
		var ret RiskPredictorCompositeConditionBase
		return ret
	}

	return o.Condition
}

// GetConditionOk returns a tuple with the Condition field value
// and a boolean to check if the value has been set.
func (o *RiskPredictorCompositeAllOfComposition) GetConditionOk() (*RiskPredictorCompositeConditionBase, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Condition, true
}

// SetCondition sets field value
func (o *RiskPredictorCompositeAllOfComposition) SetCondition(v RiskPredictorCompositeConditionBase) {
	o.Condition = v
}

// GetLevel returns the Level field value
func (o *RiskPredictorCompositeAllOfComposition) GetLevel() EnumRiskLevel {
	if o == nil {
		var ret EnumRiskLevel
		return ret
	}

	return o.Level
}

// GetLevelOk returns a tuple with the Level field value
// and a boolean to check if the value has been set.
func (o *RiskPredictorCompositeAllOfComposition) GetLevelOk() (*EnumRiskLevel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Level, true
}

// SetLevel sets field value
func (o *RiskPredictorCompositeAllOfComposition) SetLevel(v EnumRiskLevel) {
	o.Level = v
}

func (o RiskPredictorCompositeAllOfComposition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskPredictorCompositeAllOfComposition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["condition"] = o.Condition
	toSerialize["level"] = o.Level
	return toSerialize, nil
}

func (o *RiskPredictorCompositeAllOfComposition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"condition",
		"level",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRiskPredictorCompositeAllOfComposition := _RiskPredictorCompositeAllOfComposition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRiskPredictorCompositeAllOfComposition)

	if err != nil {
		return err
	}

	*o = RiskPredictorCompositeAllOfComposition(varRiskPredictorCompositeAllOfComposition)

	return err
}

type NullableRiskPredictorCompositeAllOfComposition struct {
	value *RiskPredictorCompositeAllOfComposition
	isSet bool
}

func (v NullableRiskPredictorCompositeAllOfComposition) Get() *RiskPredictorCompositeAllOfComposition {
	return v.value
}

func (v *NullableRiskPredictorCompositeAllOfComposition) Set(val *RiskPredictorCompositeAllOfComposition) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskPredictorCompositeAllOfComposition) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskPredictorCompositeAllOfComposition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskPredictorCompositeAllOfComposition(val *RiskPredictorCompositeAllOfComposition) *NullableRiskPredictorCompositeAllOfComposition {
	return &NullableRiskPredictorCompositeAllOfComposition{value: val, isSet: true}
}

func (v NullableRiskPredictorCompositeAllOfComposition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskPredictorCompositeAllOfComposition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


