/*
PingOne Platform API - PingOne Risk

The PingOne Platform API covering the PingOne Risk service

API version: 2023-06-29
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package risk

import (
	"encoding/json"
)

// checks if the RiskPolicySetTargetsCondition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskPolicySetTargetsCondition{}

// RiskPolicySetTargetsCondition Used to specify the conditions for applying the policy - the type of flows, the user groups, and the applications that are being accessed.
type RiskPolicySetTargetsCondition struct {
	// Array of the conditions for applying the policy. It is mandatory to include in the array the relevant transaction types. The relevant user groups and applications are optional. Each element in the array contains the target transaction types/user groups/applications and the event attribute that is checked.
	And []RiskPolicySetTargetsConditionAndInner `json:"and,omitempty"`
}

// NewRiskPolicySetTargetsCondition instantiates a new RiskPolicySetTargetsCondition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskPolicySetTargetsCondition() *RiskPolicySetTargetsCondition {
	this := RiskPolicySetTargetsCondition{}
	return &this
}

// NewRiskPolicySetTargetsConditionWithDefaults instantiates a new RiskPolicySetTargetsCondition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskPolicySetTargetsConditionWithDefaults() *RiskPolicySetTargetsCondition {
	this := RiskPolicySetTargetsCondition{}
	return &this
}

// GetAnd returns the And field value if set, zero value otherwise.
func (o *RiskPolicySetTargetsCondition) GetAnd() []RiskPolicySetTargetsConditionAndInner {
	if o == nil || IsNil(o.And) {
		var ret []RiskPolicySetTargetsConditionAndInner
		return ret
	}
	return o.And
}

// GetAndOk returns a tuple with the And field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskPolicySetTargetsCondition) GetAndOk() ([]RiskPolicySetTargetsConditionAndInner, bool) {
	if o == nil || IsNil(o.And) {
		return nil, false
	}
	return o.And, true
}

// HasAnd returns a boolean if a field has been set.
func (o *RiskPolicySetTargetsCondition) HasAnd() bool {
	if o != nil && !IsNil(o.And) {
		return true
	}

	return false
}

// SetAnd gets a reference to the given []RiskPolicySetTargetsConditionAndInner and assigns it to the And field.
func (o *RiskPolicySetTargetsCondition) SetAnd(v []RiskPolicySetTargetsConditionAndInner) {
	o.And = v
}

func (o RiskPolicySetTargetsCondition) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskPolicySetTargetsCondition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.And) {
		toSerialize["and"] = o.And
	}
	return toSerialize, nil
}

type NullableRiskPolicySetTargetsCondition struct {
	value *RiskPolicySetTargetsCondition
	isSet bool
}

func (v NullableRiskPolicySetTargetsCondition) Get() *RiskPolicySetTargetsCondition {
	return v.value
}

func (v *NullableRiskPolicySetTargetsCondition) Set(val *RiskPolicySetTargetsCondition) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskPolicySetTargetsCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskPolicySetTargetsCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskPolicySetTargetsCondition(val *RiskPolicySetTargetsCondition) *NullableRiskPolicySetTargetsCondition {
	return &NullableRiskPolicySetTargetsCondition{value: val, isSet: true}
}

func (v NullableRiskPolicySetTargetsCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskPolicySetTargetsCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
