/*
PingOne Platform API - PingOne Verify

The PingOne Platform API covering the PingOne Verify service

API version: 2023-07-20
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package verify

import (
	"encoding/json"
)

// checks if the OTPDeviceConfigurationOtpDeliveries type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OTPDeviceConfigurationOtpDeliveries{}

// OTPDeviceConfigurationOtpDeliveries OTP delivery configuration.
type OTPDeviceConfigurationOtpDeliveries struct {
	// Count of OTP deliveries.
	Count int32 `json:"count"`
	Cooldown OTPDeviceConfigurationOtpDeliveriesCooldown `json:"cooldown"`
}

// NewOTPDeviceConfigurationOtpDeliveries instantiates a new OTPDeviceConfigurationOtpDeliveries object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOTPDeviceConfigurationOtpDeliveries(count int32, cooldown OTPDeviceConfigurationOtpDeliveriesCooldown) *OTPDeviceConfigurationOtpDeliveries {
	this := OTPDeviceConfigurationOtpDeliveries{}
	this.Count = count
	this.Cooldown = cooldown
	return &this
}

// NewOTPDeviceConfigurationOtpDeliveriesWithDefaults instantiates a new OTPDeviceConfigurationOtpDeliveries object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOTPDeviceConfigurationOtpDeliveriesWithDefaults() *OTPDeviceConfigurationOtpDeliveries {
	this := OTPDeviceConfigurationOtpDeliveries{}
	return &this
}

// GetCount returns the Count field value
func (o *OTPDeviceConfigurationOtpDeliveries) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *OTPDeviceConfigurationOtpDeliveries) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *OTPDeviceConfigurationOtpDeliveries) SetCount(v int32) {
	o.Count = v
}

// GetCooldown returns the Cooldown field value
func (o *OTPDeviceConfigurationOtpDeliveries) GetCooldown() OTPDeviceConfigurationOtpDeliveriesCooldown {
	if o == nil {
		var ret OTPDeviceConfigurationOtpDeliveriesCooldown
		return ret
	}

	return o.Cooldown
}

// GetCooldownOk returns a tuple with the Cooldown field value
// and a boolean to check if the value has been set.
func (o *OTPDeviceConfigurationOtpDeliveries) GetCooldownOk() (*OTPDeviceConfigurationOtpDeliveriesCooldown, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cooldown, true
}

// SetCooldown sets field value
func (o *OTPDeviceConfigurationOtpDeliveries) SetCooldown(v OTPDeviceConfigurationOtpDeliveriesCooldown) {
	o.Cooldown = v
}

func (o OTPDeviceConfigurationOtpDeliveries) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OTPDeviceConfigurationOtpDeliveries) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["cooldown"] = o.Cooldown
	return toSerialize, nil
}

type NullableOTPDeviceConfigurationOtpDeliveries struct {
	value *OTPDeviceConfigurationOtpDeliveries
	isSet bool
}

func (v NullableOTPDeviceConfigurationOtpDeliveries) Get() *OTPDeviceConfigurationOtpDeliveries {
	return v.value
}

func (v *NullableOTPDeviceConfigurationOtpDeliveries) Set(val *OTPDeviceConfigurationOtpDeliveries) {
	v.value = val
	v.isSet = true
}

func (v NullableOTPDeviceConfigurationOtpDeliveries) IsSet() bool {
	return v.isSet
}

func (v *NullableOTPDeviceConfigurationOtpDeliveries) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOTPDeviceConfigurationOtpDeliveries(val *OTPDeviceConfigurationOtpDeliveries) *NullableOTPDeviceConfigurationOtpDeliveries {
	return &NullableOTPDeviceConfigurationOtpDeliveries{value: val, isSet: true}
}

func (v NullableOTPDeviceConfigurationOtpDeliveries) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOTPDeviceConfigurationOtpDeliveries) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


