/*
PingOne Platform API - PingOne Verify

The PingOne Platform API covering the PingOne Verify service

API version: 2023-07-20
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package verify

import (
	"encoding/json"
	"time"
)

// checks if the VoicePhraseContents type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VoicePhraseContents{}

// VoicePhraseContents struct for VoicePhraseContents
type VoicePhraseContents struct {
	// Deprecated
	Id          *string                        `json:"id,omitempty"`
	Environment *ObjectEnvironment             `json:"environment,omitempty"`
	VoicePhrase VoicePhraseContentsVoicePhrase `json:"voicePhrase"`
	// Deprecated
	Locale string `json:"locale"`
	// Deprecated
	Content   string     `json:"content"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// NewVoicePhraseContents instantiates a new VoicePhraseContents object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVoicePhraseContents(voicePhrase VoicePhraseContentsVoicePhrase, locale string, content string) *VoicePhraseContents {
	this := VoicePhraseContents{}
	this.VoicePhrase = voicePhrase
	this.Locale = locale
	this.Content = content
	return &this
}

// NewVoicePhraseContentsWithDefaults instantiates a new VoicePhraseContents object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVoicePhraseContentsWithDefaults() *VoicePhraseContents {
	this := VoicePhraseContents{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
// Deprecated
func (o *VoicePhraseContents) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *VoicePhraseContents) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *VoicePhraseContents) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
// Deprecated
func (o *VoicePhraseContents) SetId(v string) {
	o.Id = &v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *VoicePhraseContents) GetEnvironment() ObjectEnvironment {
	if o == nil || IsNil(o.Environment) {
		var ret ObjectEnvironment
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoicePhraseContents) GetEnvironmentOk() (*ObjectEnvironment, bool) {
	if o == nil || IsNil(o.Environment) {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *VoicePhraseContents) HasEnvironment() bool {
	if o != nil && !IsNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given ObjectEnvironment and assigns it to the Environment field.
func (o *VoicePhraseContents) SetEnvironment(v ObjectEnvironment) {
	o.Environment = &v
}

// GetVoicePhrase returns the VoicePhrase field value
func (o *VoicePhraseContents) GetVoicePhrase() VoicePhraseContentsVoicePhrase {
	if o == nil {
		var ret VoicePhraseContentsVoicePhrase
		return ret
	}

	return o.VoicePhrase
}

// GetVoicePhraseOk returns a tuple with the VoicePhrase field value
// and a boolean to check if the value has been set.
func (o *VoicePhraseContents) GetVoicePhraseOk() (*VoicePhraseContentsVoicePhrase, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VoicePhrase, true
}

// SetVoicePhrase sets field value
func (o *VoicePhraseContents) SetVoicePhrase(v VoicePhraseContentsVoicePhrase) {
	o.VoicePhrase = v
}

// GetLocale returns the Locale field value
// Deprecated
func (o *VoicePhraseContents) GetLocale() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value
// and a boolean to check if the value has been set.
// Deprecated
func (o *VoicePhraseContents) GetLocaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Locale, true
}

// SetLocale sets field value
// Deprecated
func (o *VoicePhraseContents) SetLocale(v string) {
	o.Locale = v
}

// GetContent returns the Content field value
// Deprecated
func (o *VoicePhraseContents) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
// Deprecated
func (o *VoicePhraseContents) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
// Deprecated
func (o *VoicePhraseContents) SetContent(v string) {
	o.Content = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *VoicePhraseContents) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoicePhraseContents) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *VoicePhraseContents) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *VoicePhraseContents) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *VoicePhraseContents) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoicePhraseContents) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *VoicePhraseContents) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *VoicePhraseContents) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o VoicePhraseContents) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VoicePhraseContents) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Environment) {
		toSerialize["environment"] = o.Environment
	}
	toSerialize["voicePhrase"] = o.VoicePhrase
	toSerialize["locale"] = o.Locale
	toSerialize["content"] = o.Content
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableVoicePhraseContents struct {
	value *VoicePhraseContents
	isSet bool
}

func (v NullableVoicePhraseContents) Get() *VoicePhraseContents {
	return v.value
}

func (v *NullableVoicePhraseContents) Set(val *VoicePhraseContents) {
	v.value = val
	v.isSet = true
}

func (v NullableVoicePhraseContents) IsSet() bool {
	return v.isSet
}

func (v *NullableVoicePhraseContents) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoicePhraseContents(val *VoicePhraseContents) *NullableVoicePhraseContents {
	return &NullableVoicePhraseContents{value: val, isSet: true}
}

func (v NullableVoicePhraseContents) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoicePhraseContents) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
