/*
PingOne Platform API - PingOne Verify

The PingOne Platform API covering the PingOne Verify service

API version: 2023-07-20
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package verify

import (
	"encoding/json"
)

// checks if the GovernmentIdConfigurationAadhaar type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GovernmentIdConfigurationAadhaar{}

// GovernmentIdConfigurationAadhaar Aadhaar configuration
type GovernmentIdConfigurationAadhaar struct {
	// Whether Aadhaar verification is enabled or not
	Enabled *bool `json:"enabled,omitempty"`
}

// NewGovernmentIdConfigurationAadhaar instantiates a new GovernmentIdConfigurationAadhaar object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGovernmentIdConfigurationAadhaar() *GovernmentIdConfigurationAadhaar {
	this := GovernmentIdConfigurationAadhaar{}
	return &this
}

// NewGovernmentIdConfigurationAadhaarWithDefaults instantiates a new GovernmentIdConfigurationAadhaar object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGovernmentIdConfigurationAadhaarWithDefaults() *GovernmentIdConfigurationAadhaar {
	this := GovernmentIdConfigurationAadhaar{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *GovernmentIdConfigurationAadhaar) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GovernmentIdConfigurationAadhaar) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *GovernmentIdConfigurationAadhaar) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *GovernmentIdConfigurationAadhaar) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o GovernmentIdConfigurationAadhaar) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GovernmentIdConfigurationAadhaar) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}

type NullableGovernmentIdConfigurationAadhaar struct {
	value *GovernmentIdConfigurationAadhaar
	isSet bool
}

func (v NullableGovernmentIdConfigurationAadhaar) Get() *GovernmentIdConfigurationAadhaar {
	return v.value
}

func (v *NullableGovernmentIdConfigurationAadhaar) Set(val *GovernmentIdConfigurationAadhaar) {
	v.value = val
	v.isSet = true
}

func (v NullableGovernmentIdConfigurationAadhaar) IsSet() bool {
	return v.isSet
}

func (v *NullableGovernmentIdConfigurationAadhaar) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGovernmentIdConfigurationAadhaar(val *GovernmentIdConfigurationAadhaar) *NullableGovernmentIdConfigurationAadhaar {
	return &NullableGovernmentIdConfigurationAadhaar{value: val, isSet: true}
}

func (v NullableGovernmentIdConfigurationAadhaar) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGovernmentIdConfigurationAadhaar) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
